### ISSUE TITLE
dPrime() documentation issue?

### ISSUE THREAD

**Issue by russellpierce** [jvcasill/lingStuff#1]
I'm a bit confused about how your dPrime function should work.  In the demo `axb` can have rows that are both a hit and a false alarm.  I think this means that each row in your dataset represents two responses, one from a presentation with the signal (the hit column) and one from a presentation without the signal (the miss column).  Would you please confirm that or correct me?

Thanks!

**Comment by jvcasillas** [comment]
Hello @russellpierce, somehow I missed this question. I'm sure you probably figured this out or found another solution, but just in case, the dPrime function requires you to convert your data to wide format (i.e., using `pivot_wider`). In other words, hits, false alarms, etc. should each have their own column. Hope that helps.
